name: Build
on:
  push:
    branches-ignore:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 14
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: yarn

      - name: QA
        run: yarn qa
